name: yqy_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+202

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_umplus: ^0.0.1 # 友盟统计封装插件
  path_provider: ^1.1.0
  open_file: ^2.1.1 # 打开文件
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0-rc
  dotted_border: 1.0.4 #  虚线边框
  dio: ^3.0.9
  event_bus: ^1.1.0
  extended_nested_scroll_view: ^0.3.6
  flutter_banner_swiper: ^0.1.4
  # 添加依赖屏幕适配
  flutter_screenutil: ^1.0.2
  pull_to_refresh: ^1.5.7 # 刷新控件
  oktoast: ^2.2.0
  fluttertoast: ^3.1.3
  fluro: ^1.6.3  # 路由跳转
  fluwx: 2.1.0 #  微信SDK相关   登陆
  gzx_dropdown_menu : ^1.0.3 # 下拉 筛选菜单
  shared_preferences: ^0.5.3+4
  image_picker: 0.6.1+10 # 照片选择
  synchronized: ^2.1.0+1
  json_annotation: ^2.0.0
  build_runner: ^1.2.8
  json_serializable: ^2.0.0
  connectivity: ^0.4.8+6 # 网络检测
  # Html Encoder/Decoder
  html_unescape: ^1.0.1+3
  flutter_staggered_animations: ^0.1.2 # 列表加载动画
    # 解析html标签
  flutter_html: ^0.11.0
     # 本地json对象存储
  localstorage: ^2.0.0
  like_button: ^0.1.9 # Button点赞效果
  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter: ^0.3.15+1
  flutter_webview_plugin: ^0.3.8
  device_info: ^0.4.0+1
  package_info: ^0.4.0+3
  permission_handler: ^3.3.0 # 动态权限申请
  flutter_spinkit: ^4.0.0  # 加载进度条动画效果
  fijkplayer: ^0.8.2
  url_launcher: ^5.4.7  # Url跳转 拨打电话
  flutter_custom_dialog: ^1.0.14 # 弹窗
 #  flutter_easyloading: ^1.1.1 # 弹窗
  share: 0.6.3+1 # 分享
  flutter_swiper: 1.1.6 # 轮播图
  flutter_plugin_pdf_viewer: 1.0.7   # PDF 查看器
  flui: 0.8.0  # UI组件库 待完善
  flutter_sticky_header: 0.4.2 # 悬停布局2
  indexed_list_view: 1.0.8  # 列表滚动到指定位置
  infinite_listview: 1.0.1+1 # 列表滚动到指定位置
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  flutter_xupdate: ^0.0.3 # App 升级更新插件
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/imgs/
      - assets/imgs/tab/
      - assets/imgs/home/
      - assets/imgs/user/
      - assets/imgs/task/
      - assets/imgs/drugs/
      - assets/imgs/login/
      - assets/imgs/live/
      - assets/imgs/shop/
      - assets/imgs/pay/
      - assets/imgs/notice/
      - data/